//
//  Copyright (c) SRG SSR. All rights reserved.
//
//  License information is available from the LICENSE file.
//

#import <SRGMediaPlayer/SRGMediaPlayer.h>

NS_ASSUME_NONNULL_BEGIN

@interface SRGMediaPlayerViewController (SRGAnalytics)

/**
 *  Same as `-[SRGMediaPlayerViewController initWithContentURL:analyticsLabels:userInfo:]`, but with an additional parameter 
 *  to supply optional analytics labels. These analytics labels are automatically sent in stream events generated by the
 *  player when it plays the media
 *
 *  @param analyticsLabels The analytics labels to send in stream events
 */
- (instancetype)initWithContentURL:(NSURL *)contentURL analyticsLabels:(nullable NSDictionary<NSString *, NSString *> *)analyticsLabels userInfo:(nullable NSDictionary *)userInfo;

@end

NS_ASSUME_NONNULL_END
